import db from '../../utils/db'
import bcrypt from 'bcryptjs'

export default defineEventHandler(async (event) => {
    // Check auth and role
    const accessToken = getCookie(event, 'access_token')
    if (!accessToken) {
        throw createError({ statusCode: 401, message: 'Chưa đăng nhập.' })
    }

    const payload = verifyAccessToken(accessToken)
    if (!payload) {
        throw createError({ statusCode: 401, message: 'Token không hợp lệ.' })
    }

    const currentUser = await db.user.findUnique({ where: { id: payload.userId } })

    if (!currentUser || currentUser.role !== 'ADMIN') {
        throw createError({ statusCode: 403, message: 'Không có quyền truy cập.' })
    }

    // Handle post request
    const body = await readBody(event)
    const { email, password, name, role } = body

    if (!email || !password) {
        throw createError({
            statusCode: 400,
            message: 'Email và mật khẩu là bắt buộc.'
        })
    }

    // Check if user exists
    const existingUser = await db.user.findUnique({
        where: { email }
    })

    if (existingUser) {
        throw createError({
            statusCode: 400,
            message: 'Email này đã được sử dụng.'
        })
    }

    // Create new user
    // ID is auto-generated by the database/application logic (e.g. USR- prefix) if configured, 
    // but looking at schema 'id' is a string @id. Let's rely on Prisma to generate or we generate a random one.
    // Wait, schema says it's auto generated from application.
    const userId = `USR-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).substr(2, 4).toUpperCase()}`

    const hashedPassword = await bcrypt.hash(password, 10)

    const newUser = await db.user.create({
        data: {
            id: userId,
            email,
            password: hashedPassword,
            name: name || null,
            role: role || 'USER'
        },
        select: {
            id: true,
            email: true,
            name: true,
            role: true,
            createdAt: true
        }
    })

    return { success: true, data: newUser }
})
